name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      redis:
        image: redis
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Ajusta la versión de PHP según tus necesidades
          tools: composer
      
      - name: Change to Laravel directory
        run: cd pocket-bar-api

      - name: Install dependencies
        run: |
          cd pocket-bar-api
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Copy .env file
        run: cp pocket-bar-api/.env.example pocket-bar-api/.env

      # - name: Set up database
      #   run: |
      #     cd pocket-bar-api
      #     php artisan config:cache
      #     sleep 10 # Espera de 10 segundos
      #     php artisan migrate --seed

      - name: Generate application key
        run: |
          cd pocket-bar-api
          php artisan key:generate

      - name: Execute tests (Unit and Feature tests) using PHPUnit
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: ./vendor/bin/phpunit
